"""
Generated gRPC proto files.
This file is auto-generated by scripts/generate_proto.py
"""

from . import ai_service_pb2, ai_service_pb2_grpc

__all__ = [
    "ai_service_pb2",
    "ai_service_pb2_grpc",
]
