# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\nai_service\"\x0f\n\rHealthRequest\"!\n\x0eHealthResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2L\n\tAiService\x12?\n\x06Health\x12\x19.ai_service.HealthRequest\x1a\x1a.ai_service.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=32
  _globals['_HEALTHREQUEST']._serialized_end=47
  _globals['_HEALTHRESPONSE']._serialized_start=49
  _globals['_HEALTHRESPONSE']._serialized_end=82
  _globals['_AISERVICE']._serialized_start=84
  _globals['_AISERVICE']._serialized_end=160
# @@protoc_insertion_point(module_scope)
