# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health/health.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'health/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..health import health_requests_pb2 as health_dot_health__requests__pb2
from ..health import health_responses_pb2 as health_dot_health__responses__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13health/health.proto\x12\x06health\x1a\x1chealth/health_requests.proto\x1a\x1dhealth/health_responses.proto2\x93\x01\n\rHealthService\x12\x37\n\x06Health\x12\x15.health.HealthRequest\x1a\x16.health.HealthResponse\x12I\n\x18HealthWithAuthentication\x12\x15.health.HealthRequest\x1a\x16.health.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHSERVICE']._serialized_start=93
  _globals['_HEALTHSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
