# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service/requests.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ai_service/requests.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61i_service/requests.proto\x12\nai_service\"\x0f\n\rHealthRequest\"U\n\x19NoteGenerationRequestItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05guide\x18\x03 \x01(\t\x12\x0e\n\x06sample\x18\x04 \x01(\t\"M\n\x15NoteGenerationRequest\x12\x34\n\x05items\x18\x01 \x03(\x0b\x32%.ai_service.NoteGenerationRequestItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service.requests_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=41
  _globals['_HEALTHREQUEST']._serialized_end=56
  _globals['_NOTEGENERATIONREQUESTITEM']._serialized_start=58
  _globals['_NOTEGENERATIONREQUESTITEM']._serialized_end=143
  _globals['_NOTEGENERATIONREQUEST']._serialized_start=145
  _globals['_NOTEGENERATIONREQUEST']._serialized_end=222
# @@protoc_insertion_point(module_scope)
